//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.8000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace cancelacion {
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CancelacionPortBinding", Namespace="http://service.sifei.cancelacion/")]
    public partial class Cancelacion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback peticionesPendientesOperationCompleted;
        
        private System.Threading.SendOrPostCallback procesarRespuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback cfdiRelacionadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaSATCFDIOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelaCFDIOperationCompleted;
        
        /// <remarks/>
        public Cancelacion() {
            this.Url = "https://sat.sifei.com.mx:9000/CancelacionSIFEI/Cancelacion";
        }
        
        /// <remarks/>
        public event peticionesPendientesCompletedEventHandler peticionesPendientesCompleted;
        
        /// <remarks/>
        public event procesarRespuestaCompletedEventHandler procesarRespuestaCompleted;
        
        /// <remarks/>
        public event cfdiRelacionadoCompletedEventHandler cfdiRelacionadoCompleted;
        
        /// <remarks/>
        public event consultaSATCFDICompletedEventHandler consultaSATCFDICompleted;
        
        /// <remarks/>
        public event cancelaCFDICompletedEventHandler cancelaCFDICompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.sifei.cancelacion/", ResponseNamespace="http://service.sifei.cancelacion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string peticionesPendientes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor) {
            object[] results = this.Invoke("peticionesPendientes", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginpeticionesPendientes(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("peticionesPendientes", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndpeticionesPendientes(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void peticionesPendientesAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor) {
            this.peticionesPendientesAsync(usuarioSIFEI, passwordSIFEI, rfcReceptor, null);
        }
        
        /// <remarks/>
        public void peticionesPendientesAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, object userState) {
            if ((this.peticionesPendientesOperationCompleted == null)) {
                this.peticionesPendientesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnpeticionesPendientesOperationCompleted);
            }
            this.InvokeAsync("peticionesPendientes", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor}, this.peticionesPendientesOperationCompleted, userState);
        }
        
        private void OnpeticionesPendientesOperationCompleted(object arg) {
            if ((this.peticionesPendientesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.peticionesPendientesCompleted(this, new peticionesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.sifei.cancelacion/", ResponseNamespace="http://service.sifei.cancelacion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string procesarRespuesta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute("folios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] folios[] folios, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] pfx, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordPfx) {
            object[] results = this.Invoke("procesarRespuesta", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        folios,
                        pfx,
                        passwordPfx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginprocesarRespuesta(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, folios[] folios, byte[] pfx, string passwordPfx, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("procesarRespuesta", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        folios,
                        pfx,
                        passwordPfx}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndprocesarRespuesta(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void procesarRespuestaAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, folios[] folios, byte[] pfx, string passwordPfx) {
            this.procesarRespuestaAsync(usuarioSIFEI, passwordSIFEI, rfcReceptor, folios, pfx, passwordPfx, null);
        }
        
        /// <remarks/>
        public void procesarRespuestaAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, folios[] folios, byte[] pfx, string passwordPfx, object userState) {
            if ((this.procesarRespuestaOperationCompleted == null)) {
                this.procesarRespuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocesarRespuestaOperationCompleted);
            }
            this.InvokeAsync("procesarRespuesta", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        folios,
                        pfx,
                        passwordPfx}, this.procesarRespuestaOperationCompleted, userState);
        }
        
        private void OnprocesarRespuestaOperationCompleted(object arg) {
            if ((this.procesarRespuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.procesarRespuestaCompleted(this, new procesarRespuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.sifei.cancelacion/", ResponseNamespace="http://service.sifei.cancelacion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cfdiRelacionado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcReceptor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string uuid, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] pfx, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordPfx) {
            object[] results = this.Invoke("cfdiRelacionado", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        rfcEmisor,
                        uuid,
                        pfx,
                        passwordPfx});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincfdiRelacionado(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, string rfcEmisor, string uuid, byte[] pfx, string passwordPfx, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cfdiRelacionado", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        rfcEmisor,
                        uuid,
                        pfx,
                        passwordPfx}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcfdiRelacionado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cfdiRelacionadoAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, string rfcEmisor, string uuid, byte[] pfx, string passwordPfx) {
            this.cfdiRelacionadoAsync(usuarioSIFEI, passwordSIFEI, rfcReceptor, rfcEmisor, uuid, pfx, passwordPfx, null);
        }
        
        /// <remarks/>
        public void cfdiRelacionadoAsync(string usuarioSIFEI, string passwordSIFEI, string rfcReceptor, string rfcEmisor, string uuid, byte[] pfx, string passwordPfx, object userState) {
            if ((this.cfdiRelacionadoOperationCompleted == null)) {
                this.cfdiRelacionadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncfdiRelacionadoOperationCompleted);
            }
            this.InvokeAsync("cfdiRelacionado", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        rfcReceptor,
                        rfcEmisor,
                        uuid,
                        pfx,
                        passwordPfx}, this.cfdiRelacionadoOperationCompleted, userState);
        }
        
        private void OncfdiRelacionadoOperationCompleted(object arg) {
            if ((this.cfdiRelacionadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cfdiRelacionadoCompleted(this, new cfdiRelacionadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.sifei.cancelacion/", ResponseNamespace="http://service.sifei.cancelacion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaSATCFDI([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string id, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string re, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rr, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string tt, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string fe) {
            object[] results = this.Invoke("consultaSATCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        id,
                        re,
                        rr,
                        tt,
                        fe});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultaSATCFDI(string usuarioSIFEI, string passwordSIFEI, string id, string re, string rr, string tt, string fe, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaSATCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        id,
                        re,
                        rr,
                        tt,
                        fe}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndconsultaSATCFDI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void consultaSATCFDIAsync(string usuarioSIFEI, string passwordSIFEI, string id, string re, string rr, string tt, string fe) {
            this.consultaSATCFDIAsync(usuarioSIFEI, passwordSIFEI, id, re, rr, tt, fe, null);
        }
        
        /// <remarks/>
        public void consultaSATCFDIAsync(string usuarioSIFEI, string passwordSIFEI, string id, string re, string rr, string tt, string fe, object userState) {
            if ((this.consultaSATCFDIOperationCompleted == null)) {
                this.consultaSATCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaSATCFDIOperationCompleted);
            }
            this.InvokeAsync("consultaSATCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSIFEI,
                        id,
                        re,
                        rr,
                        tt,
                        fe}, this.consultaSATCFDIOperationCompleted, userState);
        }
        
        private void OnconsultaSATCFDIOperationCompleted(object arg) {
            if ((this.consultaSATCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaSATCFDICompleted(this, new consultaSATCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.sifei.cancelacion/", ResponseNamespace="http://service.sifei.cancelacion/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelaCFDI([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioSIFEI, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordSifei, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string rfcEmisor, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)] byte[] pfx, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string passwordPfx, [System.Xml.Serialization.XmlElementAttribute("uuids", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] string[] uuids) {
            object[] results = this.Invoke("cancelaCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSifei,
                        rfcEmisor,
                        pfx,
                        passwordPfx,
                        uuids});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelaCFDI(string usuarioSIFEI, string passwordSifei, string rfcEmisor, byte[] pfx, string passwordPfx, string[] uuids, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelaCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSifei,
                        rfcEmisor,
                        pfx,
                        passwordPfx,
                        uuids}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelaCFDI(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelaCFDIAsync(string usuarioSIFEI, string passwordSifei, string rfcEmisor, byte[] pfx, string passwordPfx, string[] uuids) {
            this.cancelaCFDIAsync(usuarioSIFEI, passwordSifei, rfcEmisor, pfx, passwordPfx, uuids, null);
        }
        
        /// <remarks/>
        public void cancelaCFDIAsync(string usuarioSIFEI, string passwordSifei, string rfcEmisor, byte[] pfx, string passwordPfx, string[] uuids, object userState) {
            if ((this.cancelaCFDIOperationCompleted == null)) {
                this.cancelaCFDIOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelaCFDIOperationCompleted);
            }
            this.InvokeAsync("cancelaCFDI", new object[] {
                        usuarioSIFEI,
                        passwordSifei,
                        rfcEmisor,
                        pfx,
                        passwordPfx,
                        uuids}, this.cancelaCFDIOperationCompleted, userState);
        }
        
        private void OncancelaCFDIOperationCompleted(object arg) {
            if ((this.cancelaCFDICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelaCFDICompleted(this, new cancelaCFDICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sifei.cancelacion/")]
    public partial class folios {
        
        private respuesta respuestaField;
        
        private bool respuestaFieldSpecified;
        
        private string uuidField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool respuestaSpecified {
            get {
                return this.respuestaFieldSpecified;
            }
            set {
                this.respuestaFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string uuid {
            get {
                return this.uuidField;
            }
            set {
                this.uuidField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.sifei.cancelacion/")]
    public enum respuesta {
        
        /// <comentarios/>
        Aceptacion,
        
        /// <comentarios/>
        Rechazo,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void peticionesPendientesCompletedEventHandler(object sender, peticionesPendientesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class peticionesPendientesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal peticionesPendientesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void procesarRespuestaCompletedEventHandler(object sender, procesarRespuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class procesarRespuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal procesarRespuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void cfdiRelacionadoCompletedEventHandler(object sender, cfdiRelacionadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cfdiRelacionadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cfdiRelacionadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void consultaSATCFDICompletedEventHandler(object sender, consultaSATCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaSATCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaSATCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void cancelaCFDICompletedEventHandler(object sender, cancelaCFDICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelaCFDICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelaCFDICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
