using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Xml.Serialization;

    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    //[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.sat.gob.mx/cfd/2")]
    //[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.sat.gob.mx/cfd/2", IsNullable = false)]

public partial class Complemento
    {
        private string tipoComprobante;
        private string cantidadLetra;

        private string cadena;

        private string encabezado;
        private string observaciones;
        private string impuestosAdicionales;

        private string uuid;
        private string fechaTimbrado;
        private string noCertificadoSAT;
        private string selloCFD;
        private string selloSAT;
        private string cadenaTFD;

        private string origen;
        private string recogerEn;
        
        private string destino;
        private string destinatario;
        private string rfcDestinatario;
        private string domicilioDestinatario;
        private string entregarEn;

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Origen
        {
            get
            {
                return this.origen;
            }
            set
            {
                this.origen = value;
            }
        }



        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string RecogerEn
        {
            get
            {
                return this.recogerEn;
            }
            set
            {
                this.recogerEn = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Destino
        {
            get
            {
                return this.destino;
            }
            set
            {
                this.destino = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Destinatario
        {
            get
            {
                return this.destinatario;
            }
            set
            {
                this.destinatario = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string RfcDestinatario
        {
            get
            {
                return this.rfcDestinatario;
            }
            set
            {
                this.rfcDestinatario = value;
            }
        }



        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string DomicilioDestinatario
        {
            get
            {
                return this.domicilioDestinatario;
            }
            set
            {
                this.domicilioDestinatario = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string EntregarEn
        {
            get
            {
                return this.entregarEn;
            }
            set
            {
                this.entregarEn = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string UUID
        {
            get
            {
                return this.uuid;
            }
            set
            {
                this.uuid = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string FechaTimbrado
        {
            get
            {
                return this.fechaTimbrado;
            }
            set
            {
                this.fechaTimbrado = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string NoCertificadoSAT
        {
            get
            {
                return this.noCertificadoSAT;
            }
            set
            {
                this.noCertificadoSAT = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string SelloCFD
        {
            get
            {
                return this.selloCFD;
            }
            set
            {
                this.selloCFD = value;
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string SelloSAT
        {
            get
            {
                return this.selloSAT;
            }
            set
            {
                this.selloSAT = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string CadenaTFD
        {
            get
            {
                return this.cadenaTFD;
            }
            set
            {
                this.cadenaTFD = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string TipoComprobante
        {
            get
            {
                return this.tipoComprobante;
            }
            set
            {
                this.tipoComprobante = value;
            }
        }



        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Cadena
        {
            get
            {
                return this.cadena;
            }
            set
            {
                this.cadena = value;
            }
        }



        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string CantidadLetra
        {
            get
            {
                return this.cantidadLetra;
            }
            set
            {
                this.cantidadLetra = value;
            }
        }


        

        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Encabezado
        {
            get
            {
                return this.encabezado;
            }
            set
            {
                this.encabezado = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string Observaciones
        {
            get
            {
                return this.observaciones;
            }
            set
            {
                this.observaciones = value;
            }
        }


        /// <comentarios/>
        [System.Xml.Serialization.XmlElement()]
        public string ImpuestosAdicionales
        {
            get
            {
                return this.impuestosAdicionales;
            }
            set
            {
                this.impuestosAdicionales = value;
            }
        }

    }
