//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfEFac.wsAdesoftSecurity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegUserSession", Namespace="http://schemas.datacontract.org/2004/07/TegogoloModel.Security")]
    [System.SerializableAttribute()]
    public partial class SegUserSession : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strRazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strRfcEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strSucursalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdEmpresa {
            get {
                return this.intIdEmpresaField;
            }
            set {
                if ((this.intIdEmpresaField.Equals(value) != true)) {
                    this.intIdEmpresaField = value;
                    this.RaisePropertyChanged("intIdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strRazonSocial {
            get {
                return this.strRazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.strRazonSocialField, value) != true)) {
                    this.strRazonSocialField = value;
                    this.RaisePropertyChanged("strRazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strRfcEmpresa {
            get {
                return this.strRfcEmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.strRfcEmpresaField, value) != true)) {
                    this.strRfcEmpresaField = value;
                    this.RaisePropertyChanged("strRfcEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strSucursal {
            get {
                return this.strSucursalField;
            }
            set {
                if ((object.ReferenceEquals(this.strSucursalField, value) != true)) {
                    this.strSucursalField = value;
                    this.RaisePropertyChanged("strSucursal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoSocialMedia", Namespace="http://schemas.datacontract.org/2004/07/TegogoloModel.Security")]
    [System.SerializableAttribute()]
    public partial class InfoSocialMedia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal decLatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal decLongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intIdEmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private wpfEFac.wsAdesoftSecurity.Marketing[] lstMarketingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strBottomLeftBannerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCopyrightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strFaceUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strLogoEmpresaUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strRightBannerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTopBannerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTwitterUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strYouTubeUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal decLatitud {
            get {
                return this.decLatitudField;
            }
            set {
                if ((this.decLatitudField.Equals(value) != true)) {
                    this.decLatitudField = value;
                    this.RaisePropertyChanged("decLatitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal decLongitud {
            get {
                return this.decLongitudField;
            }
            set {
                if ((this.decLongitudField.Equals(value) != true)) {
                    this.decLongitudField = value;
                    this.RaisePropertyChanged("decLongitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intIdEmpresa {
            get {
                return this.intIdEmpresaField;
            }
            set {
                if ((this.intIdEmpresaField.Equals(value) != true)) {
                    this.intIdEmpresaField = value;
                    this.RaisePropertyChanged("intIdEmpresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public wpfEFac.wsAdesoftSecurity.Marketing[] lstMarketing {
            get {
                return this.lstMarketingField;
            }
            set {
                if ((object.ReferenceEquals(this.lstMarketingField, value) != true)) {
                    this.lstMarketingField = value;
                    this.RaisePropertyChanged("lstMarketing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strBottomLeftBannerUrl {
            get {
                return this.strBottomLeftBannerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strBottomLeftBannerUrlField, value) != true)) {
                    this.strBottomLeftBannerUrlField = value;
                    this.RaisePropertyChanged("strBottomLeftBannerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCopyright {
            get {
                return this.strCopyrightField;
            }
            set {
                if ((object.ReferenceEquals(this.strCopyrightField, value) != true)) {
                    this.strCopyrightField = value;
                    this.RaisePropertyChanged("strCopyright");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strFaceUrl {
            get {
                return this.strFaceUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strFaceUrlField, value) != true)) {
                    this.strFaceUrlField = value;
                    this.RaisePropertyChanged("strFaceUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strLogoEmpresaUrl {
            get {
                return this.strLogoEmpresaUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strLogoEmpresaUrlField, value) != true)) {
                    this.strLogoEmpresaUrlField = value;
                    this.RaisePropertyChanged("strLogoEmpresaUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strRightBannerUrl {
            get {
                return this.strRightBannerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strRightBannerUrlField, value) != true)) {
                    this.strRightBannerUrlField = value;
                    this.RaisePropertyChanged("strRightBannerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTopBannerUrl {
            get {
                return this.strTopBannerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strTopBannerUrlField, value) != true)) {
                    this.strTopBannerUrlField = value;
                    this.RaisePropertyChanged("strTopBannerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strTwitterUrl {
            get {
                return this.strTwitterUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strTwitterUrlField, value) != true)) {
                    this.strTwitterUrlField = value;
                    this.RaisePropertyChanged("strTwitterUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strYouTubeUrl {
            get {
                return this.strYouTubeUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strYouTubeUrlField, value) != true)) {
                    this.strYouTubeUrlField = value;
                    this.RaisePropertyChanged("strYouTubeUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Marketing", Namespace="http://schemas.datacontract.org/2004/07/TegogoloModel.Security")]
    [System.SerializableAttribute()]
    public partial class Marketing : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strBannerUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strBannerUrl {
            get {
                return this.strBannerUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.strBannerUrlField, value) != true)) {
                    this.strBannerUrlField = value;
                    this.RaisePropertyChanged("strBannerUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strText {
            get {
                return this.strTextField;
            }
            set {
                if ((object.ReferenceEquals(this.strTextField, value) != true)) {
                    this.strTextField = value;
                    this.RaisePropertyChanged("strText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="wsAdesoftSecurity.ServiceSecurity")]
    public interface ServiceSecurity {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceSecurity/getUser", ReplyAction="urn:ServiceSecurity/getUserResponse")]
        wpfEFac.wsAdesoftSecurity.SegUserSession getUser(string strUser, string strPasswd);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceSecurity/getSocialMedia", ReplyAction="urn:ServiceSecurity/getSocialMediaResponse")]
        wpfEFac.wsAdesoftSecurity.InfoSocialMedia getSocialMedia(string intIdEmpresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ServiceSecurity/verifyUser", ReplyAction="urn:ServiceSecurity/verifyUserResponse")]
        string verifyUser(string strRFC, string user, string passwd, int idPac);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSecurityChannel : wpfEFac.wsAdesoftSecurity.ServiceSecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSecurityClient : System.ServiceModel.ClientBase<wpfEFac.wsAdesoftSecurity.ServiceSecurity>, wpfEFac.wsAdesoftSecurity.ServiceSecurity {
        
        public ServiceSecurityClient() {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public wpfEFac.wsAdesoftSecurity.SegUserSession getUser(string strUser, string strPasswd) {
            return base.Channel.getUser(strUser, strPasswd);
        }
        
        public wpfEFac.wsAdesoftSecurity.InfoSocialMedia getSocialMedia(string intIdEmpresa) {
            return base.Channel.getSocialMedia(intIdEmpresa);
        }
        
        public string verifyUser(string strRFC, string user, string passwd, int idPac) {
            return base.Channel.verifyUser(strRFC, user, passwd, idPac);
        }
    }
}
